### PR TITLE
Add unit tests for cursor

### PR DESCRIPTION
**Pull request by hyperxor**

### CODE REVIEW

**Comment by kiplingw** [comment]
Thanks @hyperxor, but your unit test fails on s390x, amd64, i386, arm64, and ppc64el. [Here](https://launchpadlibrarian.net/462838204/buildlog_ubuntu-focal-amd64.pistache_0.0.002-202001310202~ubuntu20.04.1_BUILDING.txt.gz) is the build log for amd64. You can see the rest of them [here](https://launchpad.net/~pistache+team/+archive/ubuntu/unstable/+packages).

**Comment by kiplingw** [comment]
Hey @dennisjenkins75. The tests aren't new. They've been in there since we first created the PPA and Debianized the source however long ago that was. The unstable PPA is configured to automatically build a snapshot after every commit. The PPA has been documented in the readme for many months.

As I've been saying for a long time, the way to do unit testing properly is the Debian way where packages are injected into a container, pull their source dependencies, build, run unit tests, and optionally with DEP-8 support test the _installed_ artifacts. When you do it this way you are going to catch many more problems and more reliably than you will with Travis. The way to do it properly is always within a replicable hermetically sealed environment with standardized tools.

On the latter note, I haven't touched anything in Travis since last we talked about it.

**Comment by hyperxor** [comment]
@kiplingw Hello, I'm so sorry for this fail. Can you check tests execution with this [change](https://github.com/oktal/pistache/pull/690)? I will think more deeply about this problem.

**Comment by kiplingw** [comment]
Thanks @hyperxor. I'll let you know if the build servers fail again as soon as their next build is triggered automatically (usually a couple hours or less after a commit). 

@dennisjenkins75, [join](https://launchpad.net/~pistache+team) the Launchpad PPA team and you'll get automatic notifications when the builds fail.

**Comment by hyperxor** [comment]
@kiplingw Ok, I see, let me know about. I hope it will be fixed, otherwise I can do it (try to fix again) in the evening (18:00 UTC).

**Comment by kiplingw** [comment]
Looks like it's still [failing](https://launchpadlibrarian.net/462897874/buildlog_ubuntu-disco-ppc64el.pistache_0.0.002-202001310202~ubuntu19.04.1_BUILDING.txt.gz), but just on `ppc64el` for Disco, Eoan, and Focal.

**Comment by hyperxor** [comment]
@kiplingw Looks like this build doesn't include my fix:
```
...
[ RUN      ] stream.test_cursor_offset_for_array
/<<PKGBUILDDIR>>/tests/stream_test.cc:149: Failure
Value of: strcmp(cursor.offset(), "efgh")
  Actual: false
Expected: true
[  FAILED  ] stream.test_cursor_offset_for_array (0 ms)
...
```
There is no `strcmp` call in `/tests/stream_test.cc:149` after my fix:
```
...
   147	  size_t shift = 4u;
   148	  cursor.advance(shift);
   149
   150	  std::string result{cursor.offset(), strlen(data) - shift};
   151	  ASSERT_EQ(result, "efgh");
   152	}
...
```

**Comment by kiplingw** [comment]
Hey @hyperxor. I suggest you consider monitoring the builds [here](https://launchpad.net/~pistache+team/+archive/ubuntu/unstable/+packages), and maybe consider joining the Launchpad team to get the automated failed build notifications.

**Comment by hyperxor** [comment]
@kiplingw Hello, I have found all pistache [builds](https://launchpad.net/~pistache+team/+archive/ubuntu/unstable/+builds?build_text=&build_state=all) on Launchpad and I see that [ppc64el](https://launchpadlibrarian.net/462991387/buildlog_ubuntu-eoan-ppc64el.pistache_0.0.002-202002010203~ubuntu19.10.1_BUILDING.txt.gz) is failed but in another test:
```
23/24 Test #12: http_server_test .................   Passed   30.04 sec
24/24 Test #24: https_server_test ................***Timeout 1500.11 sec
Running main() from /build/googletest-DTPjhg/googletest-1.8.1/googletest/src/gtest_main.cc
[==========] Running 6 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 6 tests from http_client_test
[ RUN      ] http_client_test.basic_tls_request
[       OK ] http_client_test.basic_tls_request (46 ms)
[ RUN      ] http_client_test.basic_tls_request_with_auth
[       OK ] http_client_test.basic_tls_request_with_auth (48 ms)
[ RUN      ] http_client_test.basic_tls_request_with_auth_no_client_cert
70367077527296:error:1417C0C7:SSL routines:tls_process_client_certificate:peer did not return a certificate:../ssl/statem/statem_srvr.c:3678:
[       OK ] http_client_test.basic_tls_request_with_auth_no_client_cert (5 ms)
[ RUN      ] http_client_test.basic_tls_request_with_auth_client_cert_not_signed


96% tests passed, 1 tests failed out of 24

Total Test time (real) = 1501.61 sec

The following tests FAILED:
	 24 - https_server_test (Timeout)
```
it's not related to my changes at all. It's a problem with cerificate, may @dennisjenkins75 knows about it?

**Comment by kiplingw** [comment]
That's a test that has been failing on and off for a long time. It's likely a race condition that pops up under unknown circumstance. Differences in thread scheduler implementations across different platforms, in this case maybe a kernel for `ppc64el` hardware, sometimes make it apparent on occasion.

**Pull request merged**
