### PR TITLE
Compilation: save debug info when compiling static lib with LTO

### PR DESCRIPTION
**Pull request by win32asm**

### CODE REVIEW

**Comment by win32asm** [comment]
fixes openSUSE builds in https://build.opensuse.org/package/show/home:win32asm/libpistache

**Comment by kiplingw** [comment]
When you're ready, please submit a PR to add the repository for your packages [here](https://github.com/oktal/pistache#other-distributions).

**Comment by win32asm** [comment]
> @kiplingw  When you're ready, please submit a PR to add the repository for your packages 

sure.
build.opensuse.org provides build infrastructure, but I can't set it up to pick sources and rebuild on github pushes yet.
Also I'd want to have https://github.com/oktal/pistache/pull/679 accepted before disclosing build location.

**Comment by kiplingw** [comment]
Thanks Vlad. Any pre-compiled package repositories for distros should be for end users, and not just for internal testing. So take your time.

**Pull request merged**
